alertmanager:
  enabled: false
server:
  image: dev.registry.pivotal.io/container-services-manager-ci/prom/prometheus
  persistentVolume:
    enabled: false
kubeStateMetrics:
  enabled: false
pushgateway:
  enabled: false
nodeExporter:
  enabled: false