alertmanager:
  enabled: false
server:
  persistentVolume:
    enabled: false
  image:
    repository: dev.registry.pivotal.io/tanzu-service-manager-ci/prom/prometheus
imagePullSecrets:
  - name: registry-secret
kubeStateMetrics:
  enabled: false
pushgateway:
  enabled: false
nodeExporter:
  enabled: false
