{{- if not .Values.customSecretName }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  name: {{ include "mysql-cluster.secretName" . }}
  labels:
    app: {{ template "mysql-cluster.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.rootPassword }}
  ROOT_PASSWORD: {{ .Values.rootPassword | b64enc | quote }}
  {{ else }}
  ROOT_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  USER: {{ .Values.appUser | b64enc | quote }}
  PASSWORD: {{ .Values.appPassword | b64enc | quote }}
  DATABASE: {{ .Values.appDatabase | b64enc | quote }}
  DB_CONNECT_URL: {{ include "mysql-cluster.dbConnectURL" . | b64enc | quote }}
{{- end }}
